shops:
  argos:
    xbox: https://www.argos.co.uk/product/9404102?clickPR=plp:1:1
    ps5: https://www.argos.co.uk/product/8349000?clickPR=plp:1:2
    jigsaw: https://www.argos.co.uk/product/9702251?clickPR=plp:2:159
